name = "cloudpaste"
main = "worker.js"
compatibility_date = "2024-11-27"

workers_dev = true

[[kv_namespaces]]
binding = "PASTE_STORE"
id = "temporary-id-12345"

[[kv_namespaces]]
binding = "UPLOAD_STATUS"
id = "temporary-id-67890"


